### ISSUE TITLE
内存泄露的问题

### ISSUE THREAD

**Issue by zmdsjtu** [ShadowCreatorSDK/ShadowSDK3.0.1#1]
您好，直接打包应用测试发现有稳定的内存泄露（大概以1M/s的速度稳定增加），有什么解决方案么？
在Action One和JIMO上问题一样。
SDK版本3.0.1
Unity版本2019
![image](https://user-images.githubusercontent.com/19178930/92115676-6130a500-ee25-11ea-88be-7121e64e9cc8.png)

**Comment by ShadowCreatorSDK** [comment]
hi:
请问unity版本多少，使用Unity2019.2.3f1因该没问题





王超群
上海影创信息科技有限公司
Shadow Creator Information Technology Co., Ltd.
软件部
手机（Mobile）：+86-189 186 90343
地址（Address）：上海浦东新区金桥经济技术开发区川桥路399弄11号楼4层 （4/F, Building No.11, Lane 399 Chuanqiao Road, Pudong, Shanghai, China）
 
发件人： emosdnaH
发送时间： 2020-09-03 20:39
收件人： ShadowCreatorSDK/ShadowSDK3.0.1
抄送： Subscribed
主题： [ShadowCreatorSDK/ShadowSDK3.0.1] 内存泄露的问题 (#1)
您好，直接打包应用测试发现有稳定的内存泄露（大概以1M/s的速度稳定增加），有什么解决方案么？
在Action One和JIMO上问题一样。
SDK版本3.0.1
Unity版本2019

**Comment by zmdsjtu** [comment]
> hi: 请问unity版本多少，使用Unity2019.2.3f1因该没问题 王超群 上海影创信息科技有限公司 Shadow Creator Information Technology Co., Ltd. 软件部 手机（Mobile）：+86-189 186 90343 地址（Address）：上海浦东新区金桥经济技术开发区川桥路399弄11号楼4层 （4/F, Building No.11, Lane 399 Chuanqiao Road, Pudong, Shanghai, China） 发件人： emosdnaH 发送时间： 2020-09-03 20:39 收件人： ShadowCreatorSDK/ShadowSDK3.0.1 抄送： Subscribed 主题： [ShadowCreatorSDK/ShadowSDK3.0.1] 内存泄露的问题 (#1) 您好，直接打包应用测试发现有稳定的内存泄露（大概以1M/s的速度稳定增加），有什么解决方案么？ 在Action One和JIMO上问题一样。 SDK版本3.0.1 Unity版本2019 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，下图的配置存在问题么？Unity用的是2019.4.7f1
![image](https://user-images.githubusercontent.com/19178930/92119769-d357b880-ee2a-11ea-88eb-0a4bad5ddefa.png)

**Comment by zmdsjtu** [comment]
降级到Unity2019.2.3f1已解决问题，感谢回复！

**Comment by zmdsjtu** [comment]
降级到Unity2019.2.3f1已解决问题，感谢回复！
